# Generated by Django 4.1.2 on 2022-10-10 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждённый'), ('new', 'Новый'), ('canseled', 'Отменённый')], default='new', max_length=254, verbose_name='Статус')),
                ('rejectreason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('product', models.ManyToManyField(related_name='order', through='demo.ItemInOrder', to='demo.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='iteminorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='iteminorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.product', verbose_name='Пользователя'),
        ),
    ]
