# Generated by Django 4.2.1 on 2023-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_iteminorder_order_remove_iteminorder_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seconds', models.IntegerField(blank=True, verbose_name='Время в секундах')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apps', models.ManyToManyField(related_name='app', to='demo.app')),
            ],
        ),
    ]
